### ISSUE TITLE
CORS Error: The request has been blocked because of the CORS policy

### ISSUE THREAD

**Issue by aluds123** [andy6804tw/2020-12th-ironman#1]
您好:

感謝你的分享讓我能跟著實作，我在"GET"的部分能正常執行，但在做到"POST"的部分遇到  "CORS Error: The request has been blocked because of the CORS policy" 這個問題，請問是否在後端要再做其他的設定?

謝謝

**Comment by andy6804tw** [comment]
Hi @aluds123 ,
你遇到的是 CORS 跨網域存取被拒絕問題。但是在我的教學程式中有在 `run.py` 加上 flask_cors。照理來說應該不會有這個錯誤才對。麻煩您再確認一下自己的程式當中是否有以下這段的程式碼。
- [參考](https://github.com/andy6804tw/2020-12th-ironman/blob/47561d4c30538019004f881addb4cd6834ca2391/25.%E4%BD%BF%E7%94%A8Python-Flask%E6%9E%B6%E8%A8%ADAPI%E5%90%A7!/Flask-API-example-with-ML-model/run.py#L9)

> 建議可以先用 Postman 進行 API 測試

**Comment by aluds123** [comment]
Hi @andy6804tw,
感謝你正麼快回覆，剛剛確認過程式中的確有flask_cors。 剛剛xgboost版本更換後就沒有遇到問題了。
非常謝謝你。 

(現在有用Postman進行測試，謝謝)
