### ISSUE TITLE
出現AttributeError: 'XGBClassifier' object has no attribute 'use_label_encoder‘

### ISSUE THREAD

**Issue by sysphcd** [andy6804tw/2020-12th-ironman#2]
i cloned your code and also implemented it locally and i got the same result AttributeError: 'XGBClassifier' object has no attribute 'use_label_encoder' . 
 I did search for the info and saw some people said some people said use xgb.train(parameters, dtrain, num_round) instead of xgboostModel.fit(X_train, y_train).  
I still got the same error.  可以幫我看看嗎? Thank you so much.

**Comment by andy6804tw** [comment]
Hi @sysphcd I think you should check your XGBoost version in your system. 
You can try the following code:

```py
import xgboost

print(xgboost.__version__)
```

here is my xgboost version in my tutorial.

![](https://i.imgur.com/SQyqHM4.png)

Maybe you should uninstall the xgb library and re-install it again(execute commands in the shell).
Similar problem [here](https://ithelp.ithome.com.tw/articles/10252007).  or you can training again and export the model replace the old one in the model folder(xgboost-iris.pgz).

```sh
pip uninstall xgboost
pip install xgboost==0.90
```

And [here](https://colab.research.google.com/drive/1pF_Fyb0yAh8JcGy8EBMI2ieF0DqfZyXN) is my tutorial running on colab.

**Comment by sysphcd** [comment]
I've just uninstall xgboost and re-install (pip install xgboost==0.90) and run python run.py. here's what i got :
<img width="1008" alt="截圖 2022-05-18 14 58 14" src="https://user-images.githubusercontent.com/97881982/169059053-e24fc8d0-a4e7-4eb9-9ce8-97451aa5e3ab.png">

**Comment by andy6804tw** [comment]
@sysphcd Hi which code you run? I need more info.

**Comment by sysphcd** [comment]
i followed your steps in [Day 24] 儲存訓練好的模型 and [Day 25] 使用Python Flask架設API吧!  then i got the first error,  so i cloned your code and ran again.   i used colab and vscode. ( Python 3.10.4  )

**Comment by sysphcd** [comment]
https://github.com/andy6804tw/2020-12th-ironman/tree/master/25.%E4%BD%BF%E7%94%A8Python-Flask%E6%9E%B6%E8%A8%ADAPI%E5%90%A7!/Flask-API-example-with-ML-model  Here's the steps i followed.

**Comment by andy6804tw** [comment]
@sysphcd Hi  
Similar problem [here](https://ithelp.ithome.com.tw/articles/10252007).  you can training model again and export the model replace the old one in the model folder(xgboost-iris.pgz).
[here](https://colab.research.google.com/drive/1pF_Fyb0yAh8JcGy8EBMI2ieF0DqfZyXN) is my tutorial running on colab. You can download and run it locally.

**Comment by sysphcd** [comment]
wow you're so fast!! thank you so much.  Let me give it a try! i will get back to you ASAP

**Comment by sysphcd** [comment]
I got it!! thank you so much!  I will have a look what i've done wrong.  thanks again. 

<img width="1013" alt="截圖 2022-05-18 15 13 11" src="https://user-images.githubusercontent.com/97881982/169062588-2d49f0e7-fee4-4896-b9b8-1ca8215bba03.png">

<img width="1103" alt="截圖 2022-05-18 15 12 40" src="https://user-images.githubusercontent.com/97881982/169062567-fbb8299e-8dee-493c-8994-55809c95bf59.png">
